/* C# test to verify C# can correctly read C++ serialized data
   This test loads the binary file generated by the C++ test
*/
using System;
using System.IO;
using bin;

// Assuming the generated struct is named StructBase (adjust if different)
public class CSharpInteropTest
{
    public static void Main(string[] args)
    {
        Console.WriteLine("========================================");
        Console.WriteLine("C# C++ Deserialization Compatibility Test");
        Console.WriteLine("========================================");
        Console.WriteLine();

        string filePath = "csharp_test_data.bin";

        if (!File.Exists(filePath))
        {
            Console.WriteLine("❌ Error: File not found: " + filePath);
            Console.WriteLine("Please run the C++ serialization test first to generate the test data.");
            Console.WriteLine();
            Console.WriteLine("Run: ./tests/cpp_serialization_check");
            return 1;
        }

        // Read the binary file
        byte[] data = File.ReadAllBytes(filePath);
        Console.WriteLine("✓ Loaded " + data.Length + " bytes from " + filePath);
        Console.WriteLine();

        // Print hex dump of first 64 bytes
        Console.WriteLine("Hex dump (first 64 bytes):");
        for (int i = 0; i < Math.Min(data.Length, 64); i++)
        {
            if (i % 16 == 0) Console.Write("    " + i.ToString("X4") + ": ");
            Console.Write(data[i].ToString("X2") + " ");
            if ((i + 1) % 16 == 0 || i == Math.Min(data.Length, 64) - 1) Console.WriteLine();
        }
        Console.WriteLine();

        // Parse field mask length (first byte)
        if (data.Length > 0)
        {
            byte fieldMaskLength = data[0];
            Console.WriteLine("Field mask length: " + fieldMaskLength + " bytes");

            if (fieldMaskLength > 0 && data.Length >= 1 + fieldMaskLength)
            {
                Console.WriteLine("Field mask bytes: " + BitConverter.ToString(data, 1, (int)fieldMaskLength));
            }
        }

        Console.WriteLine();
        Console.WriteLine("Reading C++ serialized data with generated StructBase class...");
        Console.WriteLine("(Note: This requires the generated StructBase class to be present)");
        Console.WriteLine();

        // Test deserialization if the struct is available
        try
        {
            // Create a MemReader from the data
            MemReader reader = new MemReader(data, (uint)data.Length);

            // Create a struct to deserialize into
            StructBase cppData = new StructBase();

            // Deserialize
            bool success = cppData.deserialize(reader);

            if (success)
            {
                Console.WriteLine("✅ C# successfully deserialized C++ data!");
                Console.WriteLine();
                Console.WriteLine("Deserialized values:");
                Console.WriteLine("  double_ = " + cppData.double_);
                Console.WriteLine("  float_ = " + cppData.float_);
                Console.WriteLine("  int64_ = " + cppData.int64_);
                Console.WriteLine("  uint64_ = " + cppData.uint64_);
                Console.WriteLine("  int32_ = " + cppData.int32_);
                Console.WriteLine("  uint32_ = " + cppData.uint32_);
                Console.WriteLine("  int16_ = " + cppData.int16_);
                Console.WriteLine("  uint16_ = " + cppData.uint16_);
                Console.WriteLine("  int8_ = " + cppData.int8_);
                Console.WriteLine("  uint8_ = " + cppData.uint8_);
                Console.WriteLine("  bool_ = " + cppData.bool_);
                Console.WriteLine("  enum_ = " + cppData.enum_);
                Console.WriteLine("  string_ = " + cppData.string_);
                Console.WriteLine();

                // Verify the data
                bool dataCorrect = true;
                dataCorrect &= (cppData.double_ == 123.456);
                dataCorrect &= (cppData.float_ == 78.9f);
                dataCorrect &= (cppData.string_ == "hello from C++");

                if (dataCorrect)
                {
                    Console.WriteLine("✅ All data values match expected values!");
                }
                else
                {
                    Console.WriteLine("❌ Data values do not match!");
                }
            }
            else
            {
                Console.WriteLine("❌ Failed to deserialize C++ data");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("❌ Exception during deserialization: " + ex.Message);
            Console.WriteLine("Stack trace: " + ex.StackTrace);
            return 1;
        }

        Console.WriteLine();
        Console.WriteLine("========================================");
        Console.WriteLine("C# Interop Test Complete");
        Console.WriteLine("========================================");

        return 0;
    }
}
